# Generated by Django 5.0.4 on 2024-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=50)),
                ('soll_spalt', models.FloatField()),
                ('sensor1_str', models.FloatField()),
                ('sensor2_str', models.FloatField()),
                ('sensor3_str', models.FloatField()),
                ('soll_kraft', models.FloatField()),
                ('kraft_sensor1', models.FloatField()),
                ('kraft_sensor2', models.FloatField()),
                ('KI_1', models.FloatField()),
                ('KI_2', models.FloatField()),
            ],
        ),
    ]
